### PR TITLE
Project refactoring for python packaging

### PR DESCRIPTION
**Pull request by GiulioRossetti**
Hi,
I refactored your project to allow the installation through pip. If you like it merge this request to the master branch.

In the README.md you can find an example of how to install the package from the repository.
My suggestion is to register an account on [Pypi](https://pypi.org/), generate a proper package and upload it there in order to allow a standard installation procedure using pip.

To generate the package, from the BiMLPA project root:

- pip install twine
- python setup.py sdist bdist_wheel
- twine upload dist/*

Best,
Giulio

PS: The only change that I made on your code is in the `output_community` function: now, instead of writing on file, returns the communities as lists (this to better integrate with cdlib).

### CODE REVIEW

**Comment by hbkt** [comment]
Thank you for refactoring!
I made some changes. Although it's not the core of the program, please check them.

**Comment by GiulioRossetti** [comment]
Checked! 
I think that, if you like, it can be merged&packaged.

**Comment by hbkt** [comment]
I have a problem with installing matplotlib.
I uploaded the package to TestPyPI and checked if I can install it.
But I couldn't install it and got the following message.
```
ERROR: Could not find a version that satisfies the requirement matplotlib (from bimlpa==0.1.1) (from versions: none)
ERROR: No matching distribution found for matplotlib (from bimlpa==0.1.1)
```
Do you know the reason?

https://test.pypi.org/project/bimlpa/

**Comment by GiulioRossetti** [comment]
That's strange: I tried the installation and it works just fine for me.

**Comment by hbkt** [comment]
Thank you for checking! I think it will works. After fixing bugs I found, I will publish on PyPI.

**Pull request merged**
